apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cache
  title: Redis Cache
  description: Redis cache for session and data caching
  tags:
    - cache
    - redis
spec:
  type: cache
  owner: group:default/platform-team
  system: backend-platform
