apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: frontend-team
  title: Frontend Team
  description: Team responsible for frontend applications and UI
spec:
  type: team
  parent: group:default/platform-team
  children:
    - group:default/mobile-team
  members: []
