apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  title: Platform Team
  description: Team responsible for platform infrastructure
spec:
  type: team
  children: []
  members:
    - alice
    - bob
