apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  title: Platform Team
  description: Team responsible for platform infrastructure
spec:
  type: team
  children:
    - group:default/frontend-team
    - group:default/backend-team
  members:
    - alice
    - bob
