apiVersion: bkstg.io/v1alpha1
kind: ScorecardDefinition
metadata:
  name: tech-health
  title: Tech Health Scorecard
spec:
  scores:
  - id: documentation
    name: Documentation Score
    description: Quality and completeness of documentation
    target_kinds:
    - Component
    - API
    min_value: 0.0
    max_value: 80.0
  - id: security
    name: Security Score
    description: Security audit and vulnerability assessment
    target_kinds:
    - Component
    - API
    - Resource
    min_value: 0.0
    max_value: 100.0
  - id: testing
    name: Testing Score
    description: Test coverage and quality
    target_kinds:
    - Component
    min_value: 0.0
    max_value: 100.0
  ranks:
  - id: production_readiness
    name: Production Readiness
    description: Readiness for production deployment (conditional rules demo)
    target_kinds:
    - Component
    score_refs:
    - security
    - testing
    entity_refs:
    - lifecycle
    - type
    rules:
    - condition: "entity.lifecycle == 'production'"
      formula: "security * 0.7 + testing * 0.3"
    - condition: "entity.type == 'service'"
      formula: "security * 0.5 + testing * 0.5"
    - formula: "min(security, testing)"
    thresholds:
    - min: 90.0
      label: Ready
    - min: 70.0
      label: Almost
    - min: 0.0
      label: Not Ready
  - id: tech_health
    name: Tech Health Rank
    description: Overall technical health (label function demo)
    target_kinds:
    - Component
    score_refs:
    - security
    - documentation
    - testing
    entity_refs:
    - lifecycle
    - tags
    label_function: |
      total = security * 0.4 + documentation * 0.3 + testing * 0.3
      if total >= 90:
          return 'S'
      elif total >= 80:
          return 'A'
      elif entity.lifecycle == 'production':
          return 'B'
      elif 'critical' in entity.tags:
          return 'C'
      else:
          return 'D'
