apiVersion: bkstg.io/v1alpha1
kind: ScorecardDefinition
metadata:
  name: tech-health
  title: Tech Health
  description: Technical health assessment for software components
status: active
spec:
  scores:
    - id: documentation
      name: Documentation Score
      description: Quality and completeness of documentation
      target_kinds:
        - Component
        - API
      min_value: 0.0
      max_value: 100.0
    - id: testing
      name: Testing Score
      description: Test coverage and quality
      target_kinds:
        - Component
      min_value: 0.0
      max_value: 100.0
    - id: maintainability
      name: Maintainability Score
      description: Code quality and technical debt
      target_kinds:
        - Component
      min_value: 0.0
      max_value: 100.0
  ranks:
    - id: tech_health
      name: Tech Health Rank
      description: Overall technical health grade
      target_kinds:
        - Component
      score_refs:
        - documentation
        - testing
        - maintainability
      formula: (documentation * 0.3 + testing * 0.4 + maintainability * 0.3)
      thresholds:
        - min: 90.0
          label: S
        - min: 80.0
          label: A
        - min: 70.0
          label: B
        - min: 60.0
          label: C
        - min: 0.0
          label: D
